"""Build the compact Ar--CF4 / Ar--N2 common IR parameter table.

This script no longer refits the IR models and no longer assigns an artificial
20% uncertainty.  It reads:
  * the central parameters from data/Parameters/*_IR_primary.csv,
  * the statistical/systematic toy uncertainties generated by
    yield_prediction_bands/ArCF4_IR_bands_toy_stat.py and
    yield_prediction_bands/ArN2_IR_bands_toy_stat.py.

Run the two IR band scripts first if you want the table to include the toy
uncertainties.
"""
from __future__ import annotations

from pathlib import Path
import numpy as np
import pandas as pd

BASE_DIR = Path(__file__).resolve().parent
ROOT_DIR = BASE_DIR.parent
DATA_DIR = ROOT_DIR / "data"
BAND_DATA_DIR = DATA_DIR / "sistematic_stadistic_data"
OUT_DIR = BASE_DIR / "tex_param"
OUT_DIR.mkdir(parents=True, exist_ok=True)

COMMON_NAMES_TEX = [
    r"$P_{\mathrm{Ar}^*\,696}$", r"$\tau_{696}$", r"$K_{\mathrm{Ar},696}$", r"$K_{\mathrm{add.},696}$",
    r"$P_{\mathrm{Ar}^*\,727}$", r"$\tau_{727}$", r"$K_{\mathrm{Ar},727}$", r"$K_{\mathrm{add.},727}$",
    r"$P_{\mathrm{Ar}^*\,750}$", r"$\tau_{750}$", r"$K_{\mathrm{Ar},750}$", r"$K_{\mathrm{add.},750}$",
    r"$P_{\mathrm{Ar}^*\,764}$", r"$\tau_{764}$", r"$K_{\mathrm{Ar},764}$", r"$K_{\mathrm{add.},764}$",
    r"$P_{\mathrm{Ar}^*\,772}$", r"$\tau_{772}$", r"$K_{\mathrm{Ar},772}$", r"$K_{\mathrm{add.},772}$",
]


def _sci(x: float, sig: int = 3) -> str:
    if x is None or not np.isfinite(x):
        return r"--"
    if x == 0:
        return r"\num{0}"
    return rf"\num{{{float(x):.{sig}g}}}"


def _asym(minus: float, plus: float, sig: int = 2) -> str:
    if not np.isfinite(minus) or not np.isfinite(plus):
        return r"--"
    return rf"$^{{+{plus:.{sig}g}}}_{{-{minus:.{sig}g}}}$"


def _load_uncertainty_table(model: str) -> pd.DataFrame:
    path = BAND_DATA_DIR / f"{model}_parameter_uncertainties.csv"
    if path.exists():
        return pd.read_csv(path)

    # Fallback: central values only from the primary-fit parameter CSV.
    # This keeps the script runnable, but it deliberately marks toy uncertainties
    # as unavailable until the band scripts are executed.
    central_path = DATA_DIR / "Parameters" / f"{model}.csv"
    if not central_path.exists():
        raise FileNotFoundError(
            f"No encuentro ni {path} ni {central_path}. Ejecuta antes los scripts de bandas."
        )
    central = pd.read_csv(central_path, index_col=0)
    return pd.DataFrame(
        {
            "parameter_name": list(central.index.astype(str)),
            "value": central["parameter"].to_numpy(dtype=float),
            "stat_minus": np.nan,
            "stat_plus": np.nan,
            "syst_minus": np.nan,
            "syst_plus": np.nan,
        }
    )


def build_table() -> str:
    cf4 = _load_uncertainty_table("ArCF4_IR_primary").iloc[:20].reset_index(drop=True)
    n2 = _load_uncertainty_table("ArN2_IR_primary").iloc[:20].reset_index(drop=True)

    lines = [
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Comparación común de parámetros IR primarios en Ar--CF$_4$ y Ar--N$_2$. Las columnas de incertidumbre separan la contribución estadística, obtenida con toys independientes punto a punto, y la sistemática, obtenida con nuisances correlacionados por línea IR.}",
        r"\label{tab:IR_common_comparison}",
        r"\resizebox{\textwidth}{!}{%",
        r"\begin{tabular}{lcccccc}",
        r"\toprule",
        r" & \multicolumn{3}{c}{Ar--CF$_4$} & \multicolumn{3}{c}{Ar--N$_2$} \\",
        r"\cmidrule(lr){2-4}\cmidrule(lr){5-7}",
        r"Parámetro & Valor & Stat. & Syst. & Valor & Stat. & Syst. \\",
        r"\midrule",
    ]

    for i, pname in enumerate(COMMON_NAMES_TEX):
        c = cf4.iloc[i]
        n = n2.iloc[i]
        lines.append(
            f"{pname} & {_sci(c['value'])} & {_asym(c['stat_minus'], c['stat_plus'])} & {_asym(c['syst_minus'], c['syst_plus'])} & "
            f"{_sci(n['value'])} & {_asym(n['stat_minus'], n['stat_plus'])} & {_asym(n['syst_minus'], n['syst_plus'])} \\")

    lines.extend([
        r"\bottomrule",
        r"\end{tabular}%",
        r"}",
        r"\end{table}",
    ])
    return "\n".join(lines)


def main() -> None:
    table = build_table()
    out = OUT_DIR / "IR_common_comparison_table.tex"
    out.write_text(table, encoding="utf-8")
    print("Tabla exportada en:", out)


if __name__ == "__main__":
    main()
