from __future__ import annotations

from dataclasses import asdict, is_dataclass
from datetime import datetime
import json
from pathlib import Path
import shutil
from typing import Any, Iterable

import pandas as pd

from .paths import ProjectPaths


class OutputManager:
    """Small output helper. User-facing outputs are PDFs and LaTeX tables only.

    Data needed by later stages belongs in ``data/cache``. JSON manifests and
    plot CSV exports are opt-in, never generated by default.
    """

    def __init__(self, project_root: str | Path | None = None, *, run_name: str | None = None):
        self.paths = ProjectPaths.from_root(project_root)
        self.paths.ensure()
        self.root = self.paths.outputs

    def directory(self, *parts: str) -> Path:
        clean = [str(part).strip().replace(" ", "_") for part in parts if str(part).strip()]
        path = self.root.joinpath(*clean)
        path.mkdir(parents=True, exist_ok=True)
        return path

    def figure_dir(self, *parts: str) -> Path:
        path = self.paths.figures.joinpath(*[str(p).strip().replace(" ", "_") for p in parts])
        path.mkdir(parents=True, exist_ok=True)
        return path

    def table_dir(self, *parts: str) -> Path:
        path = self.paths.tables.joinpath(*[str(p).strip().replace(" ", "_") for p in parts])
        path.mkdir(parents=True, exist_ok=True)
        return path

    def cache_dir(self, *parts: str) -> Path:
        path = self.paths.cache.joinpath(*[str(p).strip().replace(" ", "_") for p in parts])
        path.mkdir(parents=True, exist_ok=True)
        return path

    def write_dataframe(self, frame: pd.DataFrame, path: str | Path, *, compression: str | None = None) -> Path:
        path = Path(path); path.parent.mkdir(parents=True, exist_ok=True)
        frame.to_csv(path, index=False, compression=compression)
        return path

    def write_json(self, payload: dict[str, Any], path: str | Path) -> Path:
        path = Path(path); path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(self._jsonable(payload), indent=2, sort_keys=True), encoding="utf-8")
        return path

    def write_manifest(self, path: str | Path, *, artifact_type: str, metadata: dict[str, Any],
                       sources: Iterable[str | Path] = ()) -> Path:
        # Compatibility method: manifests are written only when explicitly enabled.
        import os
        if os.environ.get("WRITE_MANIFESTS", "0").lower() not in {"1", "true", "yes", "on"}:
            return Path(path)
        return self.write_json({"artifact_type": artifact_type, "metadata": metadata,
                                "sources": [str(Path(s)) for s in sources]}, path)

    def sync_tree(self, source: str | Path, destination: str | Path, *, replace: bool = False,
                  suffixes: tuple[str, ...] | None = None) -> Path:
        source, destination = Path(source), Path(destination)
        if not source.exists(): return destination
        if replace and destination.exists(): shutil.rmtree(destination)
        destination.mkdir(parents=True, exist_ok=True)
        for path in source.rglob("*"):
            if not path.is_file(): continue
            if suffixes and path.suffix.lower() not in suffixes: continue
            out = destination / path.relative_to(source)
            out.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, out)
        return destination

    def archive_outputs(self, tag: str | None = None) -> Path:
        stamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        destination = self.paths.archive / (f"{stamp}_{tag}" if tag else stamp)
        destination.mkdir(parents=True, exist_ok=False)
        for name in ("figures", "tables"):
            source = self.paths.outputs / name
            if source.exists(): shutil.copytree(source, destination / name)
        return destination

    archive_current = archive_outputs

    @classmethod
    def _jsonable(cls, value: Any) -> Any:
        if is_dataclass(value): return cls._jsonable(asdict(value))
        if isinstance(value, Path): return str(value)
        if isinstance(value, dict): return {str(k): cls._jsonable(v) for k, v in value.items()}
        if isinstance(value, (list, tuple, set)): return [cls._jsonable(v) for v in value]
        if hasattr(value, "item"):
            try: return value.item()
            except Exception: pass
        return value
