from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
import subprocess
from typing import Iterable, Mapping

from .style_config import style_environment


@dataclass(frozen=True)
class PipelineSelection:
    analysis: bool = False
    fits: bool = False
    primary: bool = False
    secondary: bool = False
    spectra: bool = False
    tables: bool = False
    diagnostics: bool = False
    toys: int = 100
    recompute_bands: bool = False
    recompute_tables: bool = False
    export_scan_data: bool = False
    archive_outputs: bool = False
    style_preset: str = "tfm"

    @property
    def products(self) -> bool:
        return any((self.primary, self.secondary, self.spectra, self.tables, self.diagnostics))

    def validate(self) -> None:
        if not any((self.analysis, self.fits, self.products)):
            raise ValueError("Select at least one stage")
        if self.toys < 1:
            raise ValueError("The number of toys must be positive")


@dataclass(frozen=True)
class PipelinePlan:
    command: tuple[str, ...]
    env: Mapping[str, str]

    def display(self) -> str:
        assignments = " ".join(f"{key}={value}" for key, value in sorted(self.env.items()))
        return f"{assignments} {' '.join(self.command)}".strip()


def build_plan(selection: PipelineSelection, project_root: str | Path | None = None) -> PipelinePlan:
    selection.validate()
    env = {
        "RUN_PRIMARY": "1" if selection.primary else "0",
        "RUN_SECONDARY": "1" if selection.secondary else "0",
        "RUN_SPECTRA": "1" if selection.spectra else "0",
        "RUN_TABLES": "1" if selection.tables else "0",
        "RUN_DIAGNOSTICS": "1" if selection.diagnostics else "0",
        "PRIMARY_FIT_N_TOYS": str(int(selection.toys)),
        "RECOMPUTE_BANDS": "1" if (selection.recompute_bands or (selection.fits and selection.primary)) else "0",
        "RECOMPUTE_TABLES": "1" if (selection.recompute_tables or (selection.fits and selection.primary)) else "0",
        "EXPORT_SCAN_DATA": "1" if selection.export_scan_data else "0",
        "ARCHIVE_OUTPUTS": "1" if selection.archive_outputs else "0",
        "SCINTILLATION_STYLE_PRESET": selection.style_preset,
    }
    if project_root is not None:
        env.update(style_environment(project_root, selection.style_preset))
    if selection.analysis or selection.fits:
        env.update({
            "RUN_ANALYSIS": "1" if selection.analysis else "0",
            "RUN_FITS": "1" if selection.fits else "0",
            "RUN_PRODUCTS": "1" if selection.products else "0",
        })
        command = ("bash", "run_all.sh")
    else:
        command = ("bash", "run_products.sh")
    return PipelinePlan(command=command, env=env)


def dependency_status(project_root: str | Path, selection: PipelineSelection) -> list[tuple[str, bool, str]]:
    root = Path(project_root).resolve()
    checks: list[tuple[str, bool, str]] = []
    if selection.analysis:
        raw = root / "data" / "raw"
        checks.append(("Raw input directory", raw.exists(), str(raw)))
    if selection.fits:
        processed = root / "data" / "processed" / "primary"
        ready = selection.analysis or (processed.exists() and any(processed.glob("*.csv")))
        detail = "generated by selected analysis stage" if selection.analysis else str(processed)
        checks.append(("Processed primary data", ready, detail))
    if selection.primary:
        fits = root / "data" / "cache" / "fits"
        ready = selection.fits or (fits.exists() and any(fits.rglob("*")))
        detail = "generated by selected fit stage" if selection.fits else str(fits)
        checks.append(("Fit cache", ready, detail))
    if selection.secondary:
        secondary = root / "data" / "processed" / "secondary"
        ready = selection.analysis or (secondary.exists() and any(secondary.rglob("*.csv")))
        detail = "generated by selected analysis stage" if selection.analysis else str(secondary)
        checks.append(("Processed secondary populations", ready, detail))
    if selection.spectra:
        spectra = root / "data" / "processed" / "spectra"
        ready = selection.analysis or (spectra.exists() and any(spectra.rglob("*")))
        detail = "generated by selected analysis stage" if selection.analysis else str(spectra)
        checks.append(("Processed spectra", ready, detail))
    return checks


def run_plan(project_root: str | Path, plan: PipelinePlan) -> Iterable[str]:
    root = Path(project_root).resolve()
    environment = os.environ.copy()
    environment.update(plan.env)
    process = subprocess.Popen(
        list(plan.command), cwd=root, env=environment,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, bufsize=1,
    )
    assert process.stdout is not None
    for line in process.stdout:
        yield line.rstrip("\n")
    code = process.wait()
    if code:
        raise subprocess.CalledProcessError(code, plan.command)
